// export const usaMapData = [
//   { id: 1, name: "Alabama", stateCode: "AL" },
//   { id: 2, name: "Alaska", stateCode: "AK" },
//   { id: 3, name: "ARKANSAS", stateCode: "AR" },
//   { id: 4, name: "ARIZONA", stateCode: "AZ" },
//   { id: 5, name: "CALIFORNIA", stateCode: "CA" },
//   { id: 6, name: "COLORADO", stateCode: "CO" },
//   { id: 7, name: "CONNECTICUT", stateCode: "CT" },
//   { id: 8, name: "DISTRICT OF COLUMBIA", stateCode: "DC" },
//   { id: 9, name: "DELAWARE", stateCode: "DE" },
//   { id: 10, name: "FLORIDA", stateCode: "FL" },
//   { id: 11, name: "GEORGIA", stateCode: "GA" },
//   { id: 12, name: "HAWAII", stateCode: "HI" },
//   { id: 13, name: "IOWA", stateCode: "IA" },
//   { id: 14, name: "IDAHO", stateCode: "ID" },
//   { id: 15, name: "ILLINOIS", stateCode: "IL" },
//   { id: 16, name: "INDIANA", stateCode: "IN" },
//   { id: 17, name: "KANSAS", stateCode: "KS" },
//   { id: 18, name: "KENTUCKY", stateCode: "KY" },
//   { id: 19, name: "LOUISIANA", stateCode: "LA" },
//   { id: 20, name: "MASSACHUSETTS", stateCode: "MA" },
//   { id: 21, name: "MARYLAND", stateCode: "MD" },
//   { id: 22, name: "MAINE", stateCode: "ME" },
//   { id: 23, name: "MICHIGAN", stateCode: "MI" },
//   { id: 24, name: "MINNESOTA", stateCode: "MN" },
//   { id: 25, name: "MISSOURI", stateCode: "MO" },
//   { id: 26, name: "MISSISSIPPI", stateCode: "MS" },
//   { id: 27, name: "MONTANA", stateCode: "MT" },
//   { id: 28, name: "NORTH CAROLINA", stateCode: "NC" },
//   { id: 29, name: "NORTH DAKOTA", stateCode: "ND" },
//   { id: 30, name: "NEBRASKA", stateCode: "NE" },
//   { id: 31, name: "NEW HAMPSHIRE", stateCode: "NH" },
//   { id: 32, name: "NEW JERSEY", stateCode: "NJ" },
//   { id: 33, name: "NEW MEXICO", stateCode: "NM" },
//   { id: 34, name: "NEVADA", stateCode: "NV" },
//   { id: 35, name: "NEW YORK", stateCode: "NY" },
//   { id: 36, name: "OHIO", stateCode: "OH" },
//   { id: 37, name: "OKLAHOMA", stateCode: "OK" },
//   { id: 38, name: "OREGON", stateCode: "OR" },
//   { id: 39, name: "PENNSYLVANIA", stateCode: "PA" },
//   { id: 40, name: "RHODE ISLAND", stateCode: "RI" },
//   { id: 41, name: "SOUTH CAROLINA", stateCode: "SC" },
//   { id: 42, name: "SOUTH DAKOTA", stateCode: "SD" },
//   { id: 43, name: "TENNESSEE", stateCode: "TN" },
//   { id: 44, name: "TEXAS", stateCode: "TX" },
//   { id: 45, name: "UTAH", stateCode: "UT" },
//   { id: 46, name: "VIRGINIA", stateCode: "VA" },
//   { id: 47, name: "VERMONT", stateCode: "VT" },
//   { id: 48, name: "WASHINGTON", stateCode: "WA" },
//   { id: 49, name: "WISCONSIN", stateCode: "WI" },
//   { id: 50, name: "WEST VIRGINIA", stateCode: "WV" },
//   { id: 51, name: "WYOMING", stateCode: "WY" },
//   // ... other states
// ];
